### ISSUE TITLE
The Road to Composing BOSH Releases

### ISSUE THREAD

**Issue by onsi** [cloudfoundry-incubator/diego-dev-notes#9]
Diego, Runtime, BOSH and PCF had a joint meeting where we discussed what composing BOSH release might look like.

We have a tentative proposal here:
https://github.com/pivotal-cf-experimental/diego-dev-notes/blob/master/proposals/bosh-deployments.md

This includes concrete baby steps for Diego.  There is no hard timeline for implementing this yet but this could be a forum for discussion.

**Comment by ematpl** [comment]
This is mostly already done, or planned by the MEGA teams. Closing.
